Add Splash module
c0nnor263wwl/Lucky_star pull request #2
Opened 2023-06-19 23:31 UTC by knabeWWA1

- Ui, added background image, loader and simple animation
 - Notification permission, added permissions for POST_NOTIFICATIONS
 - DataStore, added DataStoreRepository.kt and MyDataStoreImpl.kt, also add communication with data store in IntroViewModel.kt
 - SDK data collection, with help of /services folder
 - Server request/response, created simple request with retrofit, added retrofit DI and call post request
 - Notification analytic
 - WorldWideWebActivity, empty web activity
 - data_for_encode.txt with proguard-rules.pro for obfuscation

2023-06-19 23:34 UTC, knabeWWA1 commented
![image](https://github.com/c0nnor263wwl/Lucky_star/assets/135615298/64844d9c-0101-4141-8077-ba87a59e2f79)

Сразу пишу про первую ошибку на скрине) Как-то не заметил и поучилось так, что кучу всего сделал в 1 коммите. Ошибка, лучше всего делать некоторое количество важных коммитов, чтобы если что было к чему откатится.

2023-06-20 08:09 UTC, c0nnor263wwl requested changes

2023-06-20 09:18 UTC, knabeWWA1 commented
Добавил фиксы к code review

2023-06-20 10:09 UTC, c0nnor263wwl approved these changes

2023-06-20 10:09 UTC, merged