Full App | CR.24.06.2023
c0nnor263wwl/Lucky_star pull request #8
Opened 2023-06-24 22:31 UTC by knabeWWA1

2023-06-26 07:00 UTC, c0nnor263wwl requested changes

2023-06-26 07:00 UTC, c0nnor263wwl commented on app/src/main/java/com/miniclip/footb/services/GlideLoader.kt
> +}
```suggestion
fun ComponentActivity.loadWithGlide(url: String?, view: ImageView) {
    lifecycleScope.launch(Dispatchers.Main.immediate){
        Glide
            .with(this@ComponentActivity)
            .load(url)
            .centerCrop()
            .into(view)
    }
}
```

2023-06-26 07:00 UTC, c0nnor263wwl commented on app/src/main/java/com/miniclip/footb/services/network/data/ResponseData.kt
> +    val push: String? = ""
```suggestion
    val url: String? =null,
    val push: String? = null
```

2023-06-26 07:00 UTC, c0nnor263wwl commented on app/src/main/java/com/miniclip/footb/ui/chat_bot/adapter/ChatGPTAdapter.kt
> +}
nit: Можно было использовать ItemViewType для отображения разных View-шек в RecyclerView

2023-06-26 07:00 UTC, c0nnor263wwl commented on app/src/main/java/com/miniclip/footb/ui/host/AppContainerActivity.kt
> +    lateinit var firebaseClient: MyConfigImpl
nit: 
```suggestion
    lateinit var firebaseClient: FirebaseConfigImpl
```

2023-06-26 07:00 UTC, c0nnor263wwl commented on app/src/main/java/com/miniclip/footb/ui/intro_screen/IntroFragment.kt
> +                    tracker = firebaseRemoteConfig.tracker, // check .isNotEmpty or .isNotBlank?
Не забыли?

2023-06-26 10:07 UTC, knabeWWA1 commented on app/src/main/java/com/miniclip/footb/ui/intro_screen/IntroFragment.kt
> +                    tracker = firebaseRemoteConfig.tracker, // check .isNotEmpty or .isNotBlank?
Хотел как раз спросить, в 8 схеме у нас есть проверка на пустоту трекера перед билдом ссылки как я помню. А тут это тоже надо? В примере схемы(KTOR_TEMPLATE) этого не видел.

2023-06-26 10:35 UTC, c0nnor263wwl commented on app/src/main/java/com/miniclip/footb/ui/intro_screen/IntroFragment.kt
> +                    tracker = firebaseRemoteConfig.tracker, // check .isNotEmpty or .isNotBlank?
Нужна, обязательно

2023-06-27 08:24 UTC, c0nnor263wwl approved these changes

2023-06-27 08:24 UTC, merged